apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: blogapp
  environment: dev

images:
  - name: khanhduy05/frontend
    newTag: "41"
  - name: khanhduy05/api-gateway
    newTag: "68"
  - name: khanhduy05/eureka-server
    newTag: "45"
  - name: khanhduy05/auth-service
    newTag: "53"    
  - name: khanhduy05/user-service
    newTag: "52"
  - name: khanhduy05/article-service
    newTag: "51"
  - name: khanhduy05/comment-service
    newTag: "47"

replicas:
  - name: frontend
    count: 1
  - name: api-gateway
    count: 1
  - name: eureka-server
    count: 1
  - name: auth-service
    count: 1
  - name: user-service
    count: 1
  - name: article-service
    count: 1
  - name: comment-service
    count: 1
  - name: postgres-db
    count: 1

