apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 16686 # Port cho giao diện Web UI
          name: ui
        - containerPort: 4317  # Port nhận gRPC từ OTel
          name: otlp-grpc
        - containerPort: 4318  # Port nhận HTTP từ OTel
          name: otlp-http