pipeline {
    agent any

    environment {
        GITHUB_REPO      = 'https://github.com/vominhduong/blogApp_cicd.git'
        BRANCH_NAME      = 'main'
        SERVICE_NAME     = 'eureka-server'
        SERVICE_PATH     = 'backend/eureka-server'
        GRADLE_MODULE    = ':backend:eureka-server'
        DOCKER_IMAGE     = 'khanhduy05/eureka-server'
        DOCKER_TAG       = "${BUILD_NUMBER}"
        DOCKER_PLATFORMS = 'linux/amd64,linux/arm64'
        SONARQUBE_SERVER = 'SonarQube'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo '========== Checkout Code =========='
                git branch: "${BRANCH_NAME}", url: "${GITHUB_REPO}"
                sh 'chmod +x gradlew'
            }
        }

        stage('Build Service') {
            steps {
                echo '========== Build API Gateway =========='
                sh "./gradlew ${GRADLE_MODULE}:clean ${GRADLE_MODULE}:build"
            }
        }

        stage('Check Build Output') {
            steps {
                echo '========== Check JAR =========='
                sh "ls -lah backend/${SERVICE_NAME}/build/libs/"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo '========== SonarQube Analysis =========='
                withSonarQubeEnv("${SONARQUBE_SERVER}") {
                    sh "./gradlew sonarqube"
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo '========== Build Docker Image =========='

                withDockerRegistry([credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/']) {
                    dir("${SERVICE_PATH}") {
                        sh """
                            docker buildx create --use --name blogapp-builder || docker buildx use blogapp-builder
                            docker buildx build --platform ${DOCKER_PLATFORMS} -t ${DOCKER_IMAGE}:${DOCKER_TAG} -t ${DOCKER_IMAGE}:latest --push .
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo '========== Pipeline Finished =========='
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed - Check logs for details'
        }
    }
}
